### PR TITLE
Fix HTTPS connection and DNS lookup issues

### PR DESCRIPTION
**Pull request by krlvm**
These changes will fix several issues:
- HTTPS connections are forwarding properly now
- Fixed DNS lookup issues by adding Google and Cloudflare DNS servers
- TunProxy should be disallowed to use its own VPN service

### CODE REVIEW

**Comment by berkayyildi** [comment]
Hi, I can not fix the domain lose issue while using Charles proxy.
Thanks for the commit I hope you to find domain losing issue.

**Comment by krlvm** [comment]
> Hi, I can not fix the domain lose issue while using Charles proxy.
> Thanks for the commit I hope you to find domain losing issue.

Do you run the proxy on the same device?

**Comment by krlvm** [comment]
I've ported fixes from the my project, try it again.

**Comment by berkayyildi** [comment]
Unfortunitely, still I can not see the domain names.
This is test screenshot with android's wifi proxy settings and tunproxy set proxy
https://imgur.com/a/xcs2ZNv

**Comment by krlvm** [comment]
> Unfortunately, still I can not see the domain names.
> This is test screenshot with android's wifi proxy settings and tunproxy set proxy.
> (Problem might be related to Charles but normally I have never see domain name error while using charles)
> test

I thought you was speaking about the domain name resolving.

There's actually is a problem: HTTPS headers, including the `Host` header, is always encrypted (they becomes encrypted after passing the proxy, in case of TunProxy - the TunProxy VPN server), so it's difficult to get the domain name; you can see only the IP address. All the magic is in [this](https://github.com/krlvm/TunProxy/blob/e919e0fd3e07111f113ad577390aceac991fe63a/android_app/app/src/main/cpp/tcp.c#L519) line - at this point you can extract the domain name yet. It becomes impossible after [the DNS lookup](https://github.com/krlvm/TunProxy/blob/e919e0fd3e07111f113ad577390aceac991fe63a/android_app/app/src/main/cpp/tcp.c#L726). If you need to get the domain name, I can suggest you to `memcpy` hostname and send it decrypted, i.e (line 735):
`sprintf(buffer, "CONNECT %s:443 HTTP/1.0\rDecryptedHost: %s\r\n\r\n", cur->tcp.hostname, decryptedHostName);`

**Comment by berkayyildi** [comment]
> > Unfortunately, still I can not see the domain names.
> > This is test screenshot with android's wifi proxy settings and tunproxy set proxy.
> > (Problem might be related to Charles but normally I have never see domain name error while using charles)
> > test
> 
> I thought you was speaking about the domain name resolving.
> There's actually is a problem: HTTPS headers, including the `Host` header, is always encrypted (they becomes encrypted after passing the proxy, in case of TunProxy - the TunProxy VPN server), so it's difficult to get the domain name; you can see only the IP address. All the magic is in [this](https://github.com/krlvm/TunProxy/blob/e919e0fd3e07111f113ad577390aceac991fe63a/android_app/app/src/main/cpp/tcp.c#L519) line - at this point you can extract the domain name yet. It becomes impossible after [the DNS lookup](https://github.com/krlvm/TunProxy/blob/e919e0fd3e07111f113ad577390aceac991fe63a/android_app/app/src/main/cpp/tcp.c#L726). If you need to get the domain name, I can suggest you to `memcpy` hostname and send it decrypted, i.e (line 735):
> `sprintf(buffer, "CONNECT %s:443 HTTP/1.0\rDecryptedHost: %s\r\n\r\n", cur->tcp.hostname, decryptedHostName);`

If I didn't get it wrong there is nothing to do for tunproxy. Problem can be fix on proxy software side, it can replace ip adress with hostname. but thank you for your attention..

**Comment by raise-isayan** [comment]
- HTTPS connections are now forwarding properly
to fix
- Fixed DNS lookup issues by adding Google and Cloudflare DNS servers
scrutiny
- TunProxy should be disallowed to use its own VPN service
research

**Comment by GaurangKorant** [comment]
Is there any way to use Https proxy with username and password using this app? if so can you guide me to some documentation or code block that i can refer to?
Thanks

**Comment by krlvm** [comment]
> * HTTPS connections are now forwarding properly
>   to fix
> * Fixed DNS lookup issues by adding Google and Cloudflare DNS servers
>   scrutiny
>   see Method: Util.getDefaultDNS
> * TunProxy should be disallowed to use its own VPN service
>   scrutiny

Looks like the latest commits implemented these fixes. Thanks!

**Pull request closed without merging**
